theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: Professor

# 对你自己的简洁描述
description: I am very enthusiastic about quantum computation and simulation. Recently, I pay attention to the quantum computation on the realistic settings.

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: Tian Chen

# 你的联系方式
phone: 

# 你的邮箱
email: chentian@bit.edu.cn

# 你目前的住址
address: Beijing, China

# 你毕业院校
school: Tsinghua University

# 你的专业
profession: Quantum computation and simulation

# 你的学位
degree: Doctor

# 你获得过的证书或奖励
credential: 
